---
# tasks file for dhcp-pxe

- name: install required packages
  dnf:
    name: dhcp-server
    state: latest

- name: stage dhcpd.conf file
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_dhcpd

- name: start dhcpd service
  service:
    name: dhcpd
    state: started
    enabled: yes

- name: configure firewalld rules
  firewalld:
    port: 67/udp
    permanent: yes
    state: enabled
  notify:
    - restart_firewalld