#!/usr/bin/python3
import os
import sys

try:
    print(os.environ['VAULT_PASSWORD'])
except KeyError:
    message = """
File     : vault_pass
Purpose  : retrieve VAULT_PASSWORD env variable
Result   : failed to retrieve VAULT_PASSWORD env variable
Solution : run the following command, replacing password
           with your vault password
Command  : export VAULT_PASSWORD=password

    """
    sys.stderr.write(message)
    exit(1)