---
# file: webserver.yml

- name: configure webservers
  hosts: webservers
  remote_user: devops
  vars_files:
    - roles/common/defaults/main.yml
  roles:
    - role: webserver
      tags: [ webserver ]