---
# tasks file for common

- name: create ansible management user
  user:
    name: "{{ users.ansible.name }}"
    state: present

- name: add ansible management user to sudoers
  lineinfile:
    path: /etc/sudoers.d/{{ users.ansible.name }}
    line: "{{ users.ansible.name }}        ALL=(ALL)       NOPASSWD: ALL"
    state: present
    create: true

- name: add ansible management user authorized key
  authorized_key:
    user: "{{ users.ansible.name }}"
    state: present
    key: "{{ lookup('file', '/home/{{ users.ansible.name }}/.ssh/id_rsa.pub') }}"